print("Please enter the number of lives")
lives = int(input())
print("please enter the energy level")
energy_level = int(input())
print("please enter the shield level")
shield_level = int(input())
print(f"{'♥'*lives}")
print(f"{'♦'*energy_level}")
print(f"{'♦'*shield_level}")